version: "3"
services:
  application:
    image: docker.io/library/actuator:0.0.1-SNAPSHOT
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      EXTERNAL_SERVICE_URL: http://138.201.180.88:8080/actuator/health
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "127.0.0.1:9090:9090"
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml